version: '3.9'
services:
  items:
    build: ./items-service
    ports:
      - "9001:8000"
    environment:
      - DB_URI=postgresql://testuser:wubalubadubdub@item-db/itemsdb
      - ENV=dev
    depends_on:
      - item-db
  
  item-db:
    image: postgres
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: wubalubadubdub 
      POSTGRES_DB: itemsdb
    volumes:
      - ./temp-db/items-db-data/:/var/lib/postgresql/data/

  keycloak-db:
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    networks:
      - local-keycloak

  keycloak:
    depends_on:
      - keycloak-db
    container_name: local_keycloak
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER} 
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db
      DB_DATABASE: ${POSTGRESQL_DB}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASSWORD: ${POSTGRESQL_PASS}
    image: jboss/keycloak:${KEYCLOAK_VERSION}
    ports:
      - "28080:8080"
    restart: unless-stopped
    networks:
      - local-keycloak

networks:
  local-keycloak:
