version: '3.9'
services:
  items:
    build: ./items-service
    container_name: items
    environment:
      - DB_URI=postgresql://testuser:wubalubadubdub@item-db/itemsdb
      - ENV=dev
    depends_on:
      - item-db
  
  item-db:
    image: postgres
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: wubalubadubdub 
      POSTGRES_DB: itemsdb
    volumes:
      - ./temp-db/items-db-data/:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d itemsdb" ]
      interval: 10s
      timeout: 45s
      retries: 10

  # grafana:
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./config/grafana
  #   ports:
  #     - "33000:3000"
  # jaeger:
  #   image: jaegertracing/all-in-one:latest
  #   ports:
  #     - "16686:16686"
  #     - "14268:14268"
  kraken_designer:
    image: devopsfaith/krakendesigner:latest
    ports:
      - 8787:80
  krakend_ce:
    image: devopsfaith/krakend:1.4.1
    volumes:
      - ./config/krakend:/etc/krakend
    ports:
      - "1234:1234"
      - "28080:8080"
      - "28090:8090"
    # depends_on:
    #   - jaeger


  # keycloak-db:
  #   image: postgres:13.2
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_DB: ${POSTGRESQL_DB}
  #     POSTGRES_USER: ${POSTGRESQL_USER}
  #     POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
  #   networks:
  #     - local-keycloak

  # keycloak:
  #   depends_on:
  #     - keycloak-db
  #   environment:
  #     KEYCLOAK_USER: ${KEYCLOAK_USER} 
  #     KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
  #     DB_VENDOR: postgres
  #     DB_ADDR: keycloak-db
  #     DB_DATABASE: ${POSTGRESQL_DB}
  #     DB_USER: ${POSTGRESQL_USER}
  #     DB_PASSWORD: ${POSTGRESQL_PASS}
  #   image: jboss/keycloak:${KEYCLOAK_VERSION}
  #   ports:
  #     - "28080:8080"
  #   restart: unless-stopped
  #   networks:
  #     - local-keycloak

networks:
  default:
    name: default-ecom-net
  local-keycloak:
