name: all build [poetry]

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry run scripts/build.sh
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: sdist-and-wheels
        path: |
          dist
